### ISSUE TITLE
Why the software history was not kept?

### ISSUE THREAD

**Issue by gustavopinto** [gandrewstone/GameMaker#2]
Hi there,

I'm a researcher studying software evolution. As part of my current research, I'm studying the implications of open-sourcing a proprietary software, for instance, if the project succeed in attracting newcomers. However, I observed that some projects, like _GameMake_, deleted their software history.

https://github.com/gandrewstone/GameMaker/commit/14940331c6e9131dc8e2adae24e8a9c9eb1f6c87

Knowing that software history is indispensable for developers (e.g., developers need to refer to history several times a day), I would like to ask GameMaker developers the following four brief questions:
1. Why did you decide to not keep the software history?
2. Do the core developers faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?
3. Do the newcomers faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?
4. How does the lack of history impacted on software evolution? Does it placed any burden in understanding and evolving the software?

Thanks in advance for your collaboration,

Gustavo Pinto, PhD
http://www.gustavopinto.org

**Comment by leilei-** [comment]
Given the age (1991-1994) it's unlikely you'd want the history. and there are doubts that the said historical codebases have been preserved well (being on media from 20+ years back)   

Also all of your mass cross-issue tracker posts are rather accusatory and don't see the full picture (and it's typical of formerly-proprietary software to go open source with a newer baseline version with no prior history from the private tree available- see also id software)

**Comment by gandrewstone** [comment]
On Thu, Jul 14, 2016 at 10:10 PM, Gustavo notifications@github.com wrote:

> Hi there,
> 
> I'm a researcher studying software evolution. As part of my current
> research, I'm studying the implications of open-sourcing a proprietary
> software, for instance, if the project succeed in attracting newcomers.
> However, I observed that some projects, like _GameMake_, deleted their
> software history.
> 
> 1494033
> https://github.com/gandrewstone/GameMaker/commit/14940331c6e9131dc8e2adae24e8a9c9eb1f6c87
> 
> Knowing that software history is indispensable for developers (e.g.,
> developers need to refer to history several times a day), I would like to
> ask GameMaker developers the following four brief questions:
> 1. Why did you decide to not keep the software history?
> 
> There were no revision control software systems on MS-DOS in the late 80s
> early 90s (AFAIK), so no history was ever recorded.
> 1. Do the core developers faced any kind of problems, when trying to
>    refer to the old history? If so, how did they solve these problems?
> 
> We lost some small but cool stuff.
> 1. Do the newcomers faced any kind of problems, when trying to refer
>    to the old history? If so, how did they solve these problems?
> 
> Unknown
> 1. How does the lack of history impacted on software evolution? Does
>    it placed any burden in understanding and evolving the software?
> 
> Developers gained great skills at "floppy-net".  Floppy-net is an ancient
> networking technique wherein you copy your code to a 3.5" floppy disk and
> then throw it like a frisbee in the general direction of its intended
> recipient.  Floppy-net experts could even cause the packet to reroute
> (curve) in mid-flight.  This technique implemented a natural "sliding
> window" protocol with the window size = the # of floppy disks lying around.

Packet loss was actually a lot smaller then you might expect due to the
3.5" disk's hard plastic case and protective metal slider.  Routing was a
problem though, and recipients (both intentional and unintentional) were
sometimes but rarely subject to a painful delivery.

Interestingly, packets are very persistent.  In fact I found one dated
4/7/91 just yesterday.  Unfortunately I lack the technology to inspect its
contents...

Regards,
Andrew

**Comment by kingIZZZY** [comment]
:laughing: someone needs to find this gem and give it the fame it deserves

**Comment by omurburuk** [comment]
Hi man! How are you this night
😀

12 Ağu 2016 ÖÖ 1:06 tarihinde "kingIZZZY" notifications@github.com yazdı:

**Comment by gustavopinto** [comment]
Hi @omurburuk, @kingIZZZY, @gandrewstone and @leilei-, 

thanks once again for answering our research inquiries. We were able to collect 35 responses and we drafted a research paper with the results. The paper was submitted and accepted for the 14th International Conference on Open Source Systems (http://oss2018.org/). You can find the paper [here](http://gustavopinto.org/lost+found/oss2018.pdf). Hope you enjoy reading the paper!

Thanks again,

Gustavo
